### ISSUE TITLE
Endpoint para desactivar donación.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#12]
Deberíamos tener un endpoint donde un voluntario le pueda pegar para avisar que no la va a poder pasar a buscar.

**Comment by lbadi** [comment]
Debería generar una notificación este endpoint?

**Comment by NicoBuch** [comment]
Si. Notificacion

**Comment by NicoBuch** [comment]
@lbadi Listo. el endpoint POST /donations/{id}/deactivate
