### ISSUE TITLE
Notificación de que pasaron los 60 minutos.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#13]
Generar una notificación cuando ya hayan pasado los 60 minutos de que el voluntario se comprometió.
Esta notificación tiene que estar dirigida al donante. La idea es que con esta notificación le preguntemos si el voluntario retiro la donación. Si no la retiro la vuelvo a abrir y si la retiro te aviso que ya la retiro.
Ademas del message_body y el n_type , esta notificación debería tener embebido la donación adentro o por lo menos el ID así se a que pegarle cuando el usuario tome una decisión . 
Ej:
{
    message_body = "Ya pasaron 60 minutos desde que pepito se comprometió a retirar la donación"
    n_type = "activation_time_passed"
    donation = { id : 21 , bla bla}
{

**Comment by NicoBuch** [comment]
@lbadi Esto esta implementado acá https://github.com/NicoBuch/social-fridge-api/blob/master/app/workers/ended_donations_updater.rb#L24

No están llegando?

**Comment by lbadi** [comment]
Perdón, no sabia que estaba implementado! ahora lo pruebo.

**Comment by lbadi** [comment]
Aparentemente no esta llegando :(

**Comment by NicoBuch** [comment]
@lbadi Mmmm, debuguie todo el codigo y parece andar bien... Cuando estés disponible lo probamos entre los dos a ver que pasa

**Comment by lbadi** [comment]
@NicoBuch Hoy no voy a estar por que ahora me tengo que ir a una fiesta, otro día lo revisamos juntos dale.

**Comment by NicoBuch** [comment]
Hola fiestero. Cuando lo podemos ver?

@lbadi

**Comment by lbadi** [comment]
@NicoBuch A esta notification le esta faltando información de la donación. Hacer que uno de los campos de la notificación sea donation_id . Sino no puedo saber a que donación enviarte los request de que se vino a buscar.

**Comment by NicoBuch** [comment]
@lbadi Ya se está enviando ese campo. Estás seguro que estás hablando de esta notificación y no de otra?
En el siguiente archivo lo podés ver. De hecho todas las notificaciones Push pasan por acá:
https://github.com/NicoBuch/social-fridge-api/blob/master/app/utils/push_json_builder.rb

**Comment by lbadi** [comment]
@NicoBuch Que raro, lo voy a volver a revisar y te digo.

**Comment by lbadi** [comment]
Ya recibo donation_id.
