### ISSUE TITLE
Situación donde voluntario se compromete a retirar una donación pero todavía no esta lista.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#14]
Un voluntario se compromete a pasar a buscar una donación, pero el tiempo pickupTimeFrom todavía no esta, es decir que todavía no se puede pasar a buscar. Al usuario le va a empezar a correr el timer para buscarla pero en realidad todavía no se puede.
Ver que hacer en esta situación, dejo abierto esto para discutirlo.

**Comment by lbadi** [comment]
Tal vez crear un nuevo estado, algo así como "waiting_for_activation" que luego sidekick cuando detecta que ya empezó la hora a partir de la cual lo podes pasar a buscar , le cambia el estado a activo. Hasta incluso este worker le puede enviar una notificación al voluntario cuando puede empezar a pasarla a buscar.

**Comment by NicoBuch** [comment]
@lbadi Yo no mostraría como `open` las donaciones que no están dentro de ese rango (pickup_time_from , pickup_time_to)

**Comment by lbadi** [comment]
Eso seria una solución fácil pero quita la posibilidad de que un voluntario pueda planificar pasar a buscar una donación. Me parece bien por ahora igual, no hay que complicársela de mas. 
Esto ya esta funcionando así ? Si es así cerra la issue.
