### ISSUE TITLE
El endpoint donator/{id}/me no da el avatar.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#15]
El endpoint para obtener mi información no me esta devolviendo el avatar. 
Sin embargo ya se lo subi y me dio un 200 OK cuando lo subo. 

Acá te dejo el link a la colección de postman, para que puedas usar las request para subir las imágenes     y para obtener la información.

https://www.getpostman.com/collections/25117244e4f9c26a8b1e

**Comment by NicoBuch** [comment]
@lbadi Probablemente sea porque S3 no esté funcionando correctamente

**Comment by NicoBuch** [comment]
@lbadi Bueno ya se puede cargar imagenes a S3 correctamente. 

EL problema parece ser la forma en la que me mandas los archivos. No los estoy detectando desde Rails. Te aviso si descubro como debería ser

**Comment by lbadi** [comment]
@NicoBuch Bueno dale, espero a que me digas como enviarlas.

**Comment by NicoBuch** [comment]
Jajajaja no se che, tienen que venir como si fuera un file input supongo
http://stackoverflow.com/questions/25518963/sending-image-text-file-from-android-to-webserver-localhost

**Comment by lbadi** [comment]
Ya lo estoy haciendo como me dijo nardi , ahora se sube OK pero sigue pasando que me da null cuando le pego a /donators/me.

**Comment by NicoBuch** [comment]
Pero me contás qué es lo que me estás mandando? Porque me llegan un monton de caracteres, con espacios en el medio.... Al menos tirame una pista jajajaja

**Comment by NicoBuch** [comment]
Por lo que vi en internet muchos lo mandan en base 64...
