### ISSUE TITLE
Volunteer null cuando hago deactivate.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#16]
https://rollbar.com/Alimentar/API/items/16/

**Comment by NicoBuch** [comment]
Ya está solucionado. No lo cierro así ves esto:

Lo que te llega en la push en este caso es: 

{ from_id: `donator_id`, donation_id: `donation_id` })

**Comment by NicoBuch** [comment]
@lbadi  Cerra el issue cuando lo hayas visto
