### ISSUE TITLE
Ubicación en la donación.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#17]
El donante debe poder cambiar la ubicación de la donación. Es decir, que cada donación deberia tener una ubicación propia (ademas de  la del donante). Esto sale del requerimiento que dijo Martin, de que cuando subo una donación, debo poder cambiar su ubicación.

**Comment by NicoBuch** [comment]
@lbadi Crees que el donante debería poder tener una ubicación variable o que la Donación en sí sea la que tenga una ubicación nueva cada vez? (Yo iría con la segunda)
