### ISSUE TITLE
Tipos de productos.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#19]
Hay que hacer un endpoint que devuelva una lista con las categorias de productos y su  correspondiente medida (kg, litro, etc).

Una posible respuesta podria ser :
[
 {
  "type" : "Panificados."
  "measure": "Kgs."
 }
 {
  "type": "No perecedero"
  "measure": "Unidades"
 }
{
   "type": "Leche"
   "measure": "Litros"
}
]

**Comment by NicoBuch** [comment]
@lbadi https://github.com/NicoBuch/social-fridge-api/commit/b77edb680ad1ed94c120c82fb69db301e263b966
