### ISSUE TITLE
Diferencia entre terminada y cancelada por el donante.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#2]
(Donante)Actualmente la única manera de terminar una donación es llamar al endpoint /donations/{id}/finish . Sin embargo las donaciones pueden terminar o bien por que el voluntario la paso a buscar o por que el donante la cancelo. Actualmente no tenemos manera de diferenciar estos dos escenarios.

**Comment by lbadi** [comment]
En realidad no hay manera como donante de cancelar una orden, ni siquiera con finish ya que actualmente solo puede llamar al finish una fridge(comedor) . Habría que cambiar para que una donación pueda ser cancelada o terminada por un donante.

**Comment by NicoBuch** [comment]
https://github.com/NicoBuch/social-fridge-api/commit/5524e3c0efc62c48b35f110b72937a091cc94277
