### ISSUE TITLE
Calificación de usuario.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#20]
Hace la feature para que el back end soporte la calificación entre los usuarios.
Esta calificación es simple, solo puede tomar dos valores (Buena o Mala) . 
La calificación se da entre cada interacción voluntario-donante. Es decir que cuando una donación se completa cada uno tiene que evaluar al otro.

Exponer dos endpoints.
Uno para que el donante, con la donación ID pueda calificar.
Otro para que el voluntario, con la donación ID pueda calificar.

EJ: POST /api/v1/qualifications
Payload:
{
donationId: 45
qualification: good/bad (1, 5).
}
Si es donante o voluntario lo podes sacar del token.

Puse (1,5) por que tal vez a vos te sea lo mismo recibir numeros en vez de string. Y yo desde el front mapeo el good como 5 y el bad como 1 (asi en un futuro es mas escalable por si lo queremos modificar).
Este endpoint es a modo de ejemplo nada mas. Podes mapearlo como gustes y pensar el back como gustes.

**Comment by NicoBuch** [comment]
@lbadi Estaba pensando en guardar la calificación en la donación. El tema es que como ahora las donaciones se convierten en anónimas, se perdería la referencia de a quien fue la calificación.

Se me ocurría capaz desnormalizar y que el usuario tenga un promedio de calificaciones que se vaya actualizando. También se podría guardar la cantidad de veces que fue calificado a parte del promedio. Que te parece? 


De lo que decís, si, me gustaría que me mandes un Int del 1 al 5. 

Ej:
POST api/v1/donations/45/qualify
{
qualification: 1
}

**Comment by NicoBuch** [comment]
check https://github.com/NicoBuch/social-fridge-api/commit/4ab62a53d909cbb9a6b0291f1cfde1da3e149cab

**Comment by lbadi** [comment]
Como prefieras. Desnormalizar a los usuarios para que ya tengan el total de calificaciones me parece perfecto asi nos ahorramos un monton de querys. Lo unico que estoy en duda es si tener a la calificación como una entidad debil o no. Por ahora no hace falta que calificación sea una entidad fuerte, pero por ahi en el futuro si queremos trabajar sobre las calificaciones estaria bueno que lo se.
Resumiendo : Esta perfecto como lo hiciste, pero si en el futuro queremos hacer mas cosas sobre la calificación creo que convendria hacerlo una entidad fuerte (con tabla.)

**Comment by lbadi** [comment]
Fijate que te puso un comentario en el commit.

**Comment by NicoBuch** [comment]
@lbadi Ya está para cerrar este PR?

**Comment by lbadi** [comment]
@NicoBuch Si cerramos este esta issue hay que crear otra por que todavia sigue sin funcionar la calificación. 
Al querer calificar me da un 500 con body: 
{
  "status": "500",
  "error": "Internal Server Error"
}

**Comment by lbadi** [comment]
@NicoBuch te cierro este enhancement request y te creo un bug.
