### ISSUE TITLE
Implementar notificaciones para voluntario.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#23]
Desde la app de android ya esta implementado el servicio de notificaciones.
Ahora falta que el backend empieze a mandar notificaciones.
Para que esto sea posible, cuando se registra un token hay que **diferenciar** de que tipo de usuario viene (donante o voluntario). Esto es necesario ya que dependiendo esto hay que usar un Secret diferente para enviar mensajes (acordarse que son dos aplicaciones independientes) .

**Comment by NicoBuch** [comment]
Armar endpoint para que puedas ir pasando la location. 
Cuando se crea una donacion hay que mandar una push a los que esten cerca. 
Agregar la validacion de que tiene que usar otro app id si es el voluntario.

**Comment by NicoBuch** [comment]
@lbadi Che ya hice todo lo que es codigo acá: 6f5a2eac3f1c19e52b5f3efe3399661d5b5e4abd

Faltaría configurar la aplicacion para las push y configurar los tokens. No recuerdo bien como lo habiamos hecho la otra vez. Sé que necesitabamos una app en firebase y una en SNS pero no recuerdo con que cuentas las habiamos hecho, y la de firebase la habias hecho vos y no se bien como configurarla. Vos te acordás?

**Comment by NicoBuch** [comment]
Se agregó el endpoint PUT /api/v1/volunteers/location donde le pasas 'lat' y 'lng' para ir actualizando su location.
Además, hay que agregar que el voluntario tambien haga el save_token que hace el donante.

**Comment by NicoBuch** [comment]
@lbadi Pudiste verlo?

**Comment by lbadi** [comment]
@NicoBuch todavia no, es mas dificil de lo que aparenta recibir periodicamente la ultima ubicación jaja. Pero estoy cerca.

**Comment by lbadi** [comment]
@NicoBuch, me esta tirando un 500 sin ninguna descripción mas que internal server error al intentar actualiar la ubicación.

**Comment by NicoBuch** [comment]
@lbadi Si, pechié. Fix acá 411d32802396411098f5d4246389f6f6ba242aa8

**Comment by lbadi** [comment]
@NicoBuch No estoy recibiendo ninguna notifiación aunque este al lado.
El voluntario esta en la location:
Longitude: -58.4652
Latitude: -34.5510
Y la donación esta siendo creada por leo5@alimentar.com que esta en el mismo lugar.
Podes revisarlo ?

**Comment by lbadi** [comment]
Listo, working and running.
