### ISSUE TITLE
Respuesta al volunteers/me

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#25]
Podras cambiar el response para que sea similar al de donator/me ?

Actualmente devuelve esto :
{
  "volunteer": {
    "email": "leonelbadi@hotmail.com",
    "name": " Leonel Badi",
    "username": "leonelbadi",
    "avatar": {
      "original": null,
      "thumb": null
    },
    "average_qualification": 0
  },
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0fQ.diPr0DYZjzjjduVJEmDCO14nCvH8mCYB3Pzhn62GR_g"
}

Lo que espero:
{
"email": "leonelbadi@hotmail.com",
    "name": " Leonel Badi",
    "username": "leonelbadi",
    "avatar": {
      "original": null,
      "thumb": null
    },
    "average_qualification": 0
}

**Comment by NicoBuch** [comment]
arreglado en 79a653cb4adc379253598f2a9d788ead560113d7
