### ISSUE TITLE
Error en Post donation.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#28]
Cuando envio este payload : 
{
	"description": "prueba1",
	"pickup_time_from": "2016-09-26T16:22:00.000-03:00",
	"pickup_time_to": "2016-09-26T17:22:00.000-03:00",
	"products_attributes" : [
		{
			"product_type_id" : 2,
			"quantity" : 1
		}
		]
}

Me devuelve un 400 con el siguiente error :

{
  "errors": [
    "Products donation translation missing: es.activerecord.errors.models.product.attributes.donation.blank"
  ]
}

**Comment by NicoBuch** [comment]
fixed in 346567b4ffd4be27df146cb216ca281a32244527
