### ISSUE TITLE
No estoy recibiendo el avatar como voluntario.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#29]
Al hacer Get volunteers/me no me esta devolviendo el avatar.

**Comment by NicoBuch** [comment]
@lbadi Por qué no? Que te devuelve? 
Es un usuario nuevo? Recordá que antes los avatares no se estaban guardando. Por lo que solo los usuarios nuevos tienen avatar.

**Comment by lbadi** [comment]
Ahh claro, uso el mismo usuario nada mas que me logeo con facebook varias veces. Mala mia.
