### ISSUE TITLE
Información sobre usuario logueado.

### ISSUE THREAD

**Issue by lbadi** [NicoBuch/social-fridge-api#3]
Actualmente no hay un endpoint para obtener la información sobre el usuario (en el caso particular donante) fogueado . Para obtener la información tengo que hacer un get a /donators que me esta devolviendo toda la lista y desde ahí filtrar en la app por el mail.
Seria conveniente hacer un endpoint donde le pasemos el token de Authorization y nos de la información del usuario fogueado.

**Comment by NicoBuch** [comment]
Fixed in https://github.com/NicoBuch/social-fridge-api/commit/fc47a98859589b5938d766a65617cf2cddc9f197
